### ISSUE TITLE
Iphone 5 Workout Description 

### ISSUE THREAD

**Issue by mattkasner** [somasole/SomaSole#101] opened 2016-07-11 17:47 UTC
![img_1833](https://cloud.githubusercontent.com/assets/19822593/16740769/6cc31ba8-4755-11e6-8daf-8663b5160588.PNG)

**Comment by mrigdon-zz** [comment] 2016-07-11 17:49
duplicate of #99

**Closed as completed by mrigdon-zz** 2016-07-11 17:49 UTC
